# Generated by Django 5.1.2 on 2024-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='agent',
            field=models.CharField(default='OldModel', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='sources',
            field=models.CharField(default='OldModel', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='suggestive_question',
            field=models.CharField(default='OldModel', max_length=100000),
            preserve_default=False,
        ),
    ]
